# Generated by Django 3.0.8 on 2020-07-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='keyword',
            field=models.CharField(default=111, max_length=25),
            preserve_default=False,
        ),
    ]
