# Generated by Django 3.0.8 on 2020-07-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appStore', models.CharField(max_length=255)),
                ('appName', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('updateTime', models.DateTimeField()),
                ('author', models.CharField(max_length=255)),
                ('downloadUrl', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('introduction', models.CharField(max_length=1500)),
                ('inList', models.CharField(max_length=25)),
                ('platform', models.CharField(max_length=25)),
                ('insertTime', models.DateTimeField()),
            ],
        ),
    ]
